### ISSUE TITLE
No Tabs UI

### ISSUE THREAD

**Issue by trixon** [dlsc-software-consulting-gmbh/WorkbenchFX#23]
Hi,
I would like to use the toolbar, drawer, dialogs and so on, but with the really simple "single module ui".

Is it possible to use WorkbenchFX without the tabs and pages, replace everything below the Workbench Toolbar?

If so, how?

**Comment by trixon** [comment]
My first intent was to insert a custom pane below the toolbar, but I ended up with a solution inspired by #7 and that's great. 

With a simple CustomTabSkin I as able to present my tabs in different ways, like the six below.

Sorry for the noise.
![2019-08-31-192406_774x509_scrot](https://user-images.githubusercontent.com/153314/64067235-b4c24e80-cc25-11e9-9fbb-e6f8917681af.png)

**Comment by martinfrancois** [comment]
Hi @trixon 
Currently, there is no way out of the box to enable kind of a "single module layout" without tabs. However, this sounds like a use case that makes sense to me.
It would make sense to default to a "one module layout" if only one module is present, since you wouldn't want to switch between modules anyways.
So this would involve adding a check and if there's only one module, it is open by default and the tab pane is removed. Feel free to open a PR!
